spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          producer:
            useNativeEncoding: true
          destination: sensors
server.port: 9009
spring.cloud.stream.kafka.binder.configuration:
  schema.registry.url: http://localhost:8017
  key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  value.serializer: sample.producer1.FooSerializer